### ISSUE TITLE
bring back JULIA_VERSION=x and JULIA_VERSION=x.y

### ISSUE THREAD

**Issue by johnnychen94** [abelsiqueira/jill#13]
#11 allows downloading specific Julia versions, while it unexpectedly introduced a breaking change that usages like the following don't work anymore.

```bash
JULIA_VERSION=1 bash -ci "$(curl -fsSL https://raw.githubusercontent.com/abelsiqueira/jill/master/jill.sh)"
```

Unfortunately, my bash knowledge stops me from fixing this. 😂

**Comment by abelsiqueira** [comment]
This was fixed in 2798b378d80e65948d3eadf5075438e4fde3eab5
