### ISSUE TITLE
Error: ./jill.sh: 23: "(" unexpected

### ISSUE THREAD

**Issue by richardkwo** [abelsiqueira/jill#2]
./jill.sh: 23: ./jill.sh: Syntax error: "(" unexpected

**Comment by abelsiqueira** [comment]
Could not reproduce. Did you use the command on the readme, or did you download and run? Could you try
```
sh jill.sh
```

**Comment by richardkwo** [comment]
I did try this.

**Comment by richardkwo** [comment]
`--version` not supported. I am using `/bin/sh` of Ubuntu 16.04.4 LTS

**Comment by abelsiqueira** [comment]
Try `bash` instead of `sh`, please.

**Comment by abelsiqueira** [comment]
I just confirmed that it should be `bash` instead of `sh` on Travis. On Arch Linux, `sh` is `bash` by default, so I missed that.

**Comment by richardkwo** [comment]
Cool. Works on `bash`.

**Comment by abelsiqueira** [comment]
Let me know if anything else breaks. Closing this one.
