### ISSUE TITLE
Feature req: copy over the old environment to the new one

### ISSUE THREAD

**Issue by affans** [abelsiqueira/jill#22]
I upgraded from 1.0 to 1.3 using this script. However, my environment files didn't copy over so I have to do it manually. It'd be great if the script can give an option to copy over environments as well.

**Comment by abelsiqueira** [comment]
Thanks for the suggestion, it could be an option in the script.

**Comment by johnnychen94** [comment]
I imagine the usage could be `bash jill.sh [-y] [-U|--upgrade]`, also, I suggest that we have a backup of previous existing `~/.julia/environments/v1.x`.
