### ISSUE TITLE
`get_latest_version` fails

### ISSUE THREAD

**Issue by blegat** [abelsiqueira/jill#26]
The script gives the following error:
```
$ bash -ci "$(curl -fsSL https://raw.githubusercontent.com/abelsiqueira/jill/master/jill.sh)"
JILL - Julia Installer 4 Linux (and MacOS) - Light
Copyright (C) 2017 Abel Soares Siqueira <abel.s.siqueira@gmail.com>
Distributed under terms of the GPLv3 license.
This script will:

  - Download latest stable Julia
  - Create a link for julia
  - Create a link for julia-VER

Download folder: /home/blegat/packages/julias
Link folder: /home/blegat/.local/bin

Do you accept these terms? (Y/N) y
--2020-03-30 16:21:09--  https://julialang.org/downloads/
Loaded CA certificate '/etc/ssl/certs/ca-certificates.crt'
Resolving julialang.org (julialang.org)... 151.101.66.49, 151.101.130.49, 151.101.2.49, ...
Connecting to julialang.org (julialang.org)|151.101.66.49|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 15203 (15K) [text/html]
Saving to: ‘page.html’

page.html                                       100%[=====================================================================================================>]  14.85K  --.-KB/s    in 0.02s   

2020-03-30 16:21:10 (843 KB/s) - ‘page.html’ saved [15203/15203]

Downloading Julia version 1.4.0
1.4.0
1.4.0
1.4.0
1.4.0
1.4.0
1.4.0
1.4.0
1.4.0
1.4.0
1.4.0
1.4.0
1.4.0
1.4.0
1.4.0
1.4.0
1.4.0
1.4.0
1.4.0
1.4.0
1.4.0
1.4.0
1.4.0
1.0.5
1.0.5
1.0.5
1.0.5
1.0.5
1.0.5
1.0.5
1.0.5
1.0.5
1.0.5
1.0.5
1.0.5
1.0.5
1.0.5
1.0.5
1.0.5
1.0.5
1.0.5
1.0.5
1.0.5
1.0.5
1.0.5
1.0.5
1.0.5
1.0.5
2.6.18
bash: [: too many arguments
already downloaded
bash: [: too many arguments
ln: target '/home/blegat/.local/bin/julia': No such file or directory
ln: target '/home/blegat/.local/bin/julia-1.4': No such file or directory
ln: target '2.6.18': No such file or directory
```
but works fine with
```
$ JULIA_VERSION=1.4.0 bash -ci "$(curl -fsSL https://raw.githubusercontent.com/abelsiqueira/jill/master/jill.sh)"
```
The line
https://github.com/abelsiqueira/jill/blob/90f83945d66048af025777d7494b36c6884046e1/jill.sh#L107
seems to rely on assumptions on the webpage of the JuliaLang download page that no longer hold.

**Comment by abelsiqueira** [comment]
Thanks for reporting @blegat, indeed it relies on assumptions on the webpage, though I might be changing that to look more like the travis script.

**Comment by blegat** [comment]
It seems the issue is that the html contains only one line so `grep "Current stable release:" page.html` does not filter out anything

**Comment by abelsiqueira** [comment]
Looking into the current html, I think I'm gonna hardcode the latest version.

**Comment by abelsiqueira** [comment]
It should be fixed now. Let me know if it doesn't work.

**Comment by johnnychen94** [comment]
FYI, not sure if it's an easy work to parse json file in bash, but there's one provided alongside with the releases https://julialang-s3.julialang.org/bin/versions.json

**Comment by johnnychen94** [comment]
FYI, not sure if it's an easy work to parse json file in bash, but there's one provided alongside with the releases https://julialang-s3.julialang.org/bin/versions.json

**Comment by abelsiqueira** [comment]
That could help, but it looks like there is no `1.4` in this json either.

**Comment by johnnychen94** [comment]
Looks like the script needs to be manually run to update the release info.

cref: https://github.com/JuliaLang/julia/issues/33817

**Comment by johnnychen94** [comment]
FYI `versions.json` is now updated and can be used to free you from manual version bumps.
