### ISSUE TITLE
Download specific version

### ISSUE THREAD

**Issue by abelsiqueira** [abelsiqueira/jill#3]
Possibly by hard-coding the download links.

**Comment by alexcanepa** [comment]
close now? nice work btw thanks for this

**Comment by abelsiqueira** [comment]
Thanks, @alexcanepa. I want to support downloading [older versions](https://julialang.org/downloads/oldreleases.html) as well, that's why this is still open.

**Comment by johnnychen94** [comment]
Unfortunately, `JULIA_VERSION=1.1` is no longer supported.

**Comment by johnnychen94** [comment]
Looks like the download url is well organized, we don't need to parse the download html:

```bash
REPOSITORY=https://julialang-s3.julialang.org/bin/
PLATFORM=linux
BIT=64
ARCH=x86_64
MINOR_VERSION=1.2
FULL_VERSION=1.2.0

URL=$(REPOSITORY)/$(PLATFORM)/x$(BIT)/$(MINOR_VERSION)/julia-$(FULL_VERSION)-$(PLATFORM)-$(ARCH).tar.gz
```

For example: `https://julialang-s3.julialang.org/bin/linux/x64/1.2/julia-1.2.0-linux-x86_64.tar.gz`

**Comment by abelsiqueira** [comment]
The parsing was mainly to get the latest version, but for specific versions, this is indeed better.

**Comment by abelsiqueira** [comment]
I think I'll try to update the script to use this. Let me know if you're working on it, so we don't duplicate efforts.

**Comment by johnnychen94** [comment]
I'm fulfilled with other jobs, it would be great if you can put hands on it!

Perhaps parsing https://julialang.org/downloads/oldreleases.html ?

**Comment by abelsiqueira** [comment]
I'll see what I can do.

**Comment by abelsiqueira** [comment]
I'm getting errors (https://travis-ci.org/abelsiqueira/jill/jobs/574431854) of the type 

```
cp: /Volumes/julia-1.2.0/Julia-1.2.app: No such file or directory
umount: /Volumes/julia-1.2.0: not currently mounted
```

any idea what could be causing it?

**Comment by johnnychen94** [comment]
No idea, I've checked https://github.com/abelsiqueira/jill/commit/0a74a9ca6f05c1e554e8afdcffd25865c76fc034 and it succeeds in my MBP v`10.14.6`

Perhaps a restart would be fine.
