### ISSUE TITLE
Document upgrading julia using jill

### ISSUE THREAD

**Issue by thautwarm** [abelsiqueira/jill#30]
how to update my julia installed by jill? within jill

**Comment by thautwarm** [comment]
seems reinvoking this script works.

**Comment by abelsiqueira** [comment]
Calling jill.sh again should install the newer version. Also, after #29, you can also pass `-u` to copy over the environment. We have to document that better, though.

**Comment by amontoison** [comment]
I will update the documentation today to explain the `-u` option. I forgot to update the README with #29.
