### ISSUE TITLE
Should JuliaLang officially support Jill?

### ISSUE THREAD

**Issue by abelsiqueira** [abelsiqueira/jill#33]
Expanding the discussion on https://github.com/JuliaLang/www.julialang.org/pull/928

It was brought up whether `jill` should be included in a more official capacity on the Julia website, and I think the discussion can happen here.

**Background**

My motivation for creating `jill` was "I want to `wget` the latest version but I forgot the url", and since I was gonna `tar` and `ln -s` that downloaded version, I figured it might as well be a bash script. Naturally, I put it online for others to use, and I thought it would be cool to have it *installable* like `brew` (One line C-c C-v). Instead, I decided it was simpler to have it only *runnable* by C-c C-v.

`jill` is actually my second attempt at a Julia version manager: https://github.com/abelsiqueira/julia-mngr. `julia-mngr` was too complicated, so my second attempt was really focused on "just get the latest".

**Official support**

I am not sure if `jill` should be **the** recommended installation procedure for Linux, as it is more complicated than the three lines required to make Julia work, but it is moving along nicely to become a versions manager. I am receiving amazing contributions, and I run it every time a new Julia release is made. I also update the badge ![Julia 1.5.0](https://img.shields.io/badge/julia-1.5.0-3a5fcc.svg?style=flat-square&logo=data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAA4AAAAOCAMAAAAolt3jAAAB+FBMVEUAAAA3lyU3liQ4mCY4mCY3lyU4lyY1liM3mCUskhlSpkIvkx0zlSEeigo5mSc8mio0liKPxYQ/nC5NozxQpUBHoDY3lyQ5mCc3lyY6mSg3lyVPpD9frVBgrVFZqUpEnjNgrVE3lyU8mio8mipWqEZhrVJgrVFfrE9JoTkAVAA3lyXJOjPMPjNZhCowmiNOoz1erE9grVFYqUhCnjFmk2KFYpqUV7KTWLDKOjK8CADORj7GJx3SJyVAmCtKojpOoz1DnzFVeVWVSLj///+UV7GVWbK8GBjPTEPMQTjPTUXQUkrQSEGZUycXmg+WXbKfZ7qgarqbYraSVLCUV7HLPDTKNy7QUEjUYVrVY1zTXFXPRz2UVLmha7upeMCqecGlcb6aYLWfaLrLPjXLPjXSWFDVZF3VY1zVYlvRTkSaWKqlcr6qesGqecGpd8CdZbjo2+7LPTTKOS/QUUnVYlvVY1zUXVbPSD6TV7OibLuqecGqecGmc76aYbaibLvKOC/SWlPMQjrQUEjRVEzPS0PLPDL7WROZX7WgarqibLucY7eTVrCVWLLLOzLGLCLQT0bIMynKOC7FJx3MPjV/Vc+odsCRUa+SVLCDPaWVWLKWWrLJOzPHOTLKPDPLPDPLOzLLPDOUV6+UV7CVWLKVWLKUV7GUWLGPUqv///8iGqajAAAAp3RSTlMAAAAAAAAAAAAAABAZBAAAAABOx9uVFQAAAB/Y////eQAAADv0////pgEAAAAAGtD///9uAAAAAAAAAAcOQbPLfxgNAAAAAAA5sMyGGg1Ht8p6CwAAFMf///94H9j///xiAAAw7////65K+f///5gAABjQ////gibg////bAAAAEfD3JwaAFfK2o0RAAAAAA4aBQAAABEZAwAAAAAAAAAAAAAAAAAAAIvMfRYAAAA6SURBVAjXtcexEUBAFAXAfTM/IDH6uAbUqkItyAQYR26zDeS0UxieBvPVbArjXd9GS295raa/Gmu/A7zfBRgv03cCAAAAAElFTkSuQmCC) everytime a new release is made, so it is kept "healthy".

The concern that `jill` is not part of the JuliaLang repo was already raised, and I agree. If the Julia team decides it's best, I have no problem moving it. I also plan to keep maintaining it for the foreseeable future, as I am now.

**Comment by mkschulze** [comment]
Would be a great move I think. I was looking for a solution like Pyenv, but couldn't find it in the first place. Got a tip to look here then and it works great.

**Comment by abelsiqueira** [comment]
@ViralBShah, @StefanKarpinski, can you confirm whether `juliaup` has been chosen as officially supported Julia installer? Thanks in advance.

**Comment by abelsiqueira** [comment]
> People are using `juliaup` and trying it out. We are fairly certain it will soon be announced as the official installer.

Well, it's good that Julia will have an official download manager, but it is a pity that it is not based on Jill or Jill.py (@johnnychen94's fork) - at least for us :)

Was there a reason for the selection? That information is useful to decide the future of Jill. I haven't followed the development of `juliaup`, but it appears to have been created around the same time as the discussion on https://github.com/JuliaLang/www.julialang.org/pull/928.

**Comment by ViralBShah** [comment]
The thinking is that we need a standalone installer that works without any dependencies on every OS - especially Windows.

**Comment by johnnychen94** [comment]
I'll respect this decision and it's delighted to see Julialang trying to make installing Julia a smoother experience by declaring official support.

I myself will still put basic maintenance efforts to keep jill.py functioning since it has quite a lot of users. Quoting from the README of jill.py

> Why I make the python fork of JILL?
> ...
> And again, I live in China so I want to rely on services that are easily accessible in China, PyPI is, GitHub and AWS S3 bucket aren't. A recent Julia installer project [juliaup](https://github.com/JuliaLang/juliaup) written in Rust solves the Python dependency problem very well, but the tradeoff is that juliaup needs its own distributing system (currently GitHub and S3 bucket) to make sure it can be reliably downloaded to user machine. And for this it just won't be as good as PyPI in the foreseeable future.

Using `juliaup` in China is still a little bit more difficult than using `jill.py`. (Maybe it's because I write jill.py 😆 )

**Comment by abelsiqueira** [comment]
> (Maybe it's because I write jill.py :laughing:  )

I sympathize. :D

**Comment by ViralBShah** [comment]
We can certainly mention alternate downloaders too on the website! Are github and S3 completely blocked in China? We do serve packages to Chinese users, right?

**Comment by johnnychen94** [comment]
> Are github and S3 completely blocked in China? We do serve packages to Chinese users, right?

The network is extremely unstable unless we use proxies/VPNs to bypass the GFW, but the dilemma here is that unless you already have a proxy, you can hardly buy a proxy.

> It would be good to understand what it takes to make the default method robust for everyone.


There is already an environment variable `JULIAUP_SERVER` for `juliaup` to download from other servers. For instance, the following usage will download tarballs from the BFSU mirror

`JULIAUP_SERVER=https://mirrors.bfsu.edu.cn/julia-releases juliaup add 1.7.2`

but for official support, I expect users should not need to set the downloading servers. Currently, without setting the downloading server, it is

```bash
...
Now installing Juliaup
Installing Julia 1.7.2+0 (x64).
  Downloading: [=>                  ] 10.53MiB/117.58MiB eta: 10m
```

**Comment by StefanKarpinski** [comment]
I'm sure we can figure out how to make juliaup work fast and reliably everywhere including China. It would be great if it didn't require any configuration but in the meantime being able to point at a mirror would work.
