### ISSUE TITLE
Allow install of release candidates

### ISSUE THREAD

**Issue by crstnbr** [abelsiqueira/jill#37]
It doesn't seem to be possible to use `jill` to download the 1.6 release candidate:

```
➜  ~/.local/bin jill download 1.6
query the latest 1.6 version, it may take seconds...
version 1.6 is not available, use latest stable release.
```

Would be great if this were supported. Also, since we already have `jill install stable` and `jill install latest` we could also add something like `jill install beta` or `jill install rc` to install the latest rc candidate. 

Update: Note that an explicit `jill download 1.6.0-rc1` works. So it seems that `jill` is only checking for stable 1.6.x versions.

**Comment by crstnbr** [comment]
Oh sorry, I think I should have opened this at the python fork... Sorry for the noise.

**Comment by abelsiqueira** [comment]
Hi @crstnbr, it is still a reasonable request for our bash version as well. Thanks for opening it. I reopened.

**Comment by abelsiqueira** [comment]
It's done. It should be possible to install the latest `rc` with
```
./jill.sh --rc
```
