### ISSUE TITLE
MacOS support

### ISSUE THREAD

**Issue by abelsiqueira** [abelsiqueira/jill#47]
@johnnychen94 after I dropped MacOS support on #39 you offered to help fix what was needed for the update.

@sdotd got in touch by e-mail to say he is available to help support MacOS.

With both of your help, I think we can bring back MacOS support to Jill.sh.

I have created a branch https://github.com/abelsiqueira/jill/tree/macos to update the support and check what is breaking. Here is the broken Github Action: https://github.com/abelsiqueira/jill/actions/runs/621647254

Thanks for the availability, I hope we can make this work.

**Comment by mkschulze** [comment]
I just cloned the repo on macOS and created an alias like `alias jup="cd ~/dev/jill && git pull && bash jill.sh"`
Seems to work fine.

**Comment by johnnychen94** [comment]
Yes, #48 brings it back so this issue was fixed already.

**Comment by abelsiqueira** [comment]
That's right, I forgot to answer this issue. Let me know if something changes @mkschulze, and thanks for the info.
