### ISSUE TITLE
Autofetch new versions with a CI trigger?

### ISSUE THREAD

**Issue by mkschulze** [abelsiqueira/jill#52]
Can the newest version somehow autofetched with a CI trigger or smth?
Would be nice if not too much work I guess.

thx

**Comment by abelsiqueira** [comment]
Hi, @mkschulze. It would be nice. I think the main places to change are the README and the ci tests.
At least for minor version changes, it would be good.

I think one way to do it would be to fetch the versions.json daily and check the last stable against the version on README/ci. Probably a modification of https://github.com/abelsiqueira/jill/blob/master/jill.sh#L69 to get only the stable versions, and some `grep` + `sed`. What do you think?

**Comment by mkschulze** [comment]
Yea, sounds great!

**Comment by abelsiqueira** [comment]
Do you want to take a shot at it?

**Comment by mkschulze** [comment]
It doesn’t sound too difficult, however I’m still at novice level. So, not sure how to start. Probably setting up a new GitHub action workflow, with a daily runner, fetching the URL, then testing against the reader and if it differs, then making a pull request for review and merge?

**Comment by abelsiqueira** [comment]
Yes, that's right. You'll probably find
[CompatHelper.yml](https://github.com/JuliaSmoothOptimizers/NLPModels.jl/blob/master/.github/workflows/CompatHelper.yml) useful. It is something that runs periodically (the `cron` can be adjusted).
The steps will probably look more like this [ci](https://github.com/abelsiqueira/jill/blob/master/.github/workflows/ci.yml#L23), and there is a "Create a pull request" action: https://github.com/JuliaSmoothOptimizers/NLPModels.jl/blob/master/.github/workflows/format_pr.yml#L19

Probably the hardest part is writing the script to fetch and update the version, testing it and making the commits necessary for the PR action. Feel free to open incomplete PRs if you want to discuss any steps. Thanks for the availability.

**Comment by johnnychen94** [comment]
It's worth noting that, after 60 days without repo activity scheduled workflows deactivate automatically.

The sustainable way IMO is to write the "fetch-and-update-the-version" logic inside the installer. jill.py now reads the https://julialang-s3.julialang.org/bin/versions.json for this job.

**Comment by abelsiqueira** [comment]
Thanks, @johnnychen94. We use the `versions.json` for the `--rc` option, but we prefer to leave the basic call with the least amount of dependencies.

**Comment by abelsiqueira** [comment]
This was implemented in #77, and I just tested with `1.9.0-rc3`.
