### ISSUE TITLE
error downloading julia-1.6-latest

### ISSUE THREAD

**Issue by thomarse-ef** [abelsiqueira/jill#53]
Trying to use this script on a Raspberry Pi Zero W. I'm getting this error: `error downloading julia-1.6-latest`. Any ideas why?

**Comment by johnnychen94** [comment]
Raspberry Pi isn't supported by jill.sh as far as I can tell: https://github.com/abelsiqueira/jill/blob/2d854a97bb7182570ac438e45b27fa7d81142f5b/jill.sh#L177-L187

You can try the Python fork jill.py instead.

**Comment by thomarse-ef** [comment]
OK thanks!

**Comment by abelsiqueira** [comment]
Hi @thomarse-ef, if you are in a rush, or prefer using Python, using jill.py should do it for you.
Otherwise, you can help me update to support Raspberry Pi. I imagine changing the function above should be enough, but you'll have to test.

**Comment by thomarse-ef** [comment]
Hi @abelsiqueira. I'm happy to test it for you - just tell me what to do!

**Comment by abelsiqueira** [comment]
Great, thanks! What do you get with these commands:
- `uname -m`
- `uname -s`

**Comment by thomarse-ef** [comment]
```
pi@raspberrypi:~ $ uname -m
armv6l
pi@raspberrypi:~ $ uname -s
Linux
```

**Comment by thomarse-ef** [comment]
I just tried jill.py, it fails because there is no `armv6l` version in https://julialang-s3.julialang.org/bin/versions.json

See the issue I opened: [https://github.com/johnnychen94/jill.py/issues/85](https://github.com/johnnychen94/jill.py/issues/85)

**Comment by abelsiqueira** [comment]
It looks like Julia doesn't have binaries for armv6, only 7 and 8. Here (https://github.com/JuliaLang/julia/blob/master/doc/build/arm.md) it says that it can be built on it, but I found no information about binaries for it.

**Comment by thomarse-ef** [comment]
OK, thanks
