### ISSUE TITLE
Wrong architecture

### ISSUE THREAD

**Issue by lrsantos11** [abelsiqueira/jill#6]
If Linux language is not english, `lscpu` will not give the right Architecture. The `jill` is downloading the 32bit version of julia.

https://github.com/abelsiqueira/jill/blob/9a1faebc0ca6b97d5b96ea5f6e6ba865894ffd08/jill.sh#L72

**Comment by abelsiqueira** [comment]
Thanks for the report. Could you check if `LC_ALL=C lscpu` prints the output in english? If not, can you post an example?

**Comment by lrsantos11** [comment]
That was exactly the solution I had in mind. Works like a charm.
```bash
lrsantos@labmac01:~$ LC_ALL=C lscpu
Architecture:        x86_64
CPU op-mode(s):      32-bit, 64-bit
Byte Order:          Little Endian
CPU(s):              12
```

---
Luiz Rafael dos Santos
@lrsantos11

**Comment by lrsantos11** [comment]
That was exactly the solution I had in mind. Works like a charm.
```bash
lrsantos@labmac01:~$ LC_ALL=C lscpu
Architecture:        x86_64
CPU op-mode(s):      32-bit, 64-bit
Byte Order:          Little Endian
CPU(s):              12
```
