### ISSUE TITLE
Issue with `vjul` directory

### ISSUE THREAD

**Issue by vnikoofard** [abelsiqueira/jill#71]
Hi,

I'm trying to update my Julia 1.7.3 installation using the following command
`sudo ./jill.sh -u julia-1.7.3
`But I get the following error
`cp: cannot stat '/root/.julia/environments/vjul': No such file or directory
`
I also had installed the version 1.7.3 using jill.

Any help is appreciated.

**Comment by abelsiqueira** [comment]
Hi @vnikoofard, can you try `-u 1.7` instead.

**Comment by abelsiqueira** [comment]
PS. Let me know if that works so I can update the documentation with something clearer.

**Comment by vnikoofard** [comment]
Now it gives the following error

`cp: cannot stat '/root/.julia/environments/v1.7': No such file or directory`

But it's strange! I have this directory in my Home
/home/vahid/.julia/environments/v1.7

**Comment by abelsiqueira** [comment]
I think this is a corner case that we missed before. We use `~` for the `-u` option, so with `sudo` is default to `/root/`.
I think a workaround is

- run without `sudo` to copy the environment
- then run again with `sudo` to actually install in the correct place.

**Comment by vnikoofard** [comment]
I'm confused, as you said `~/.julia/environments/v1.7` is pointing to `/home/vahid/.julia/environments/v1.7` in command line.

**Comment by abelsiqueira** [comment]
I think I got it now. Try `sudo -E ./jill.sh -u 1.7`.

The explanation is from https://unix.stackexchange.com/questions/684395/tilde-expansion-vs-variables-in-bash.

It looks like `sudo` does not preserve your `$HOME` information, so it uses the roots `$HOME`, which is `/root`.
If you run with `-E`, it will use your `$HOME`, which is `/home/vahid`.

To test this, create a `tmp.sh` file with the contents `echo ~`, and run

```shell
bash tmp.sh
sudo bash tmp.sh
sudo -E bash tmp.sh
```

In my case it returned

```shell
/home/abel
/root
/home/abel
```

**Comment by vnikoofard** [comment]
Excellent solution! Thanks Abel! Now the upgrading works fine.
Muito obrigado!

**Comment by abelsiqueira** [comment]
Ah, great news. I will try to improve the documentation for this case. Thanks for reporting this.
Also, could you leave your opinion on
- #69 
This will help direct future work on Jill.

**Comment by vnikoofard** [comment]
Ah, just one more comment. After upgrading to 1.8 and copying the environments using jill, to update the package using Pkg it throws an error 
`ERROR: SystemError: opening file "/home/vahid/.julia/environments/v1.8/Manifest.toml": Permission denied
`
The workaround is run the Julia using `sudo`.

**Comment by abelsiqueira** [comment]
Thanks for the report.

**Comment by abelsiqueira** [comment]
To fix this you can change the ownership of the files in your environments like this:

```shell
sudo chown -R vahid:users ~/.julia/environments/v1.8
```

Check with `ls -l` in that folder.
