### ISSUE TITLE
jill does not install julia-1.90

### ISSUE THREAD

**Issue by murrayE** [abelsiqueira/jill#80]
Previously I used jill under macOS to install julia-1.8.5. Today neither "jill.sh" nor "jill.sh -v 1.90" installs the latest julia, namely, 1.90. The first does nothing; the second, while giving the message "Try to download julia version '1.90", gives error "cp: julia-1.9/Julia-1.9.app: No such file or directory".

What's wrong?

**Comment by abelsiqueira** [comment]
Hi @murrayE, it should be `1.9.0` instead of `1.90`.
For the normal usage to download `1.8.5`, you have to download the latest version of `jill.sh`. Either clone or curl again, please.

**Comment by murrayE** [comment]
OK, I curl'ed jill again, executed "jill.sh", saw message "Try to download julia version '1.9-latest", but still when I execute "julia --version" or just start "julia", it is version 1.8.5. (However, Julia.app was installed, and if I use the app, it does start julia 1.9.0.)

**Comment by abelsiqueira** [comment]
> What, then, is the real point of using jill to upgrade to latest julia version if one must download a new version of jill to do it?

I find it easier to upgrade `jill` (`git pull`) or use `jill -v 1.9.0`, than what I was doing before. Your experience may vary, I don't know what you did before using jill.
Jill is free software, built on contributors free time. If you want to work on this feature, let's talk about it in a new issue.

> The problem seems to be that the link /usr/local/bin/julia still points to
/Applications/Julia-1.8.app/Contents/Resources/julia/bin/julia.

Did you use `sudo` to install? Maybe you did in the past and not now? Does the equivalent `1.9` path exists?

The OSX installation is contributed code, and I don't use OSX, so I can't test your case. Fell free to give more information.

**Comment by murrayE** [comment]
> Did you use `sudo` to install? Maybe you did in the past and not now? Does the equivalent `1.9` path exists?

That was the issue, and including `sudo` for the `jill.sh` command fixed the link, so that now executing `juilia` at the command-line prompt does indeed start julia 1.9.0.

Thanks!
