### ISSUE TITLE
Problemas na instalação kali no Android

### ISSUE THREAD

**Issue by Dhezao** [abelsiqueira/jill#84]
![Screenshot_20230925_003900_Termux](https://github.com/abelsiqueira/jill/assets/123648704/277f554b-ef8a-4125-88ec-9088d333d040)

Preciso de ajuda!
Estou no processo de aprendizado. 

Modelo SM-G985F (y2sxx)
Fabricante samsung S20+

**Comment by abelsiqueira** [comment]
@Dhezao, este repositório é sobre Julia, não tem a ver com Kali ou Android. Eu não sei nada a respeito, então não posso nem lhe sugerir onde buscar ajuda. Acho que é de volta ao Google, infelizmente. Boa sorte na busca
